language: c
sudo: required
before_install:
  - sudo apt-get install gfortran-5

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./bin/toastexample1
  - ./bin/toastexample2

after_success:
  - bash <(curl -s https://codecov.io/bash)
